services:
  web:
    image: lonewolfrex/bookmyflight:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DB_NAME: ${DB_NAME}
      - DB_USER: ${DB_USER}
      - DB_PASS: ${DB_PASS}
      - DB_HOST: ${DB_HOST}
      - DB_PORT: ${DB_PORT}
    depends_on:
      - db
    networks:
      - webnet
  nginx:
    build: ./nginx
    image: nginx:alpine
    container_name: nginx-api-gateway
    ports:
      - "8080:80"
      - "443:443"                        
    depends_on:
      - web
    networks:
      - webnet
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB: ${DB_NAME}
      - POSTGRES_USER: ${DB_USER}
      - POSTGRES_PASSWORD: = ${DB_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

volumes:
  pgdata:

