# Unique key in SonarQube
sonar.projectKey=bookmyflight

# Display name in UI
sonar.projectName=bookmyflight

# Version (optional)
sonar.projectVersion=1.0

# Source code location (relative to this file)
sonar.sources=.

# Exclude Django artifacts (optional)
sonar.exclusions=
  **/venv/**,
  **/*.pyc,
  **/migrations/*.py,
  static/**,
  .vscode/**,
  .gitignore